api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api
    name_prefix: api_

controllers:
    resource: ../../src/Controller/App
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
